query PopularMoviesQuery($page: Int) {
  popularMovies(entityId: $entityId) {
    id
    name
    type
    annualGrossRevenue
    dateOfFormation
    fsaRecordAnswers {
      moduleId
      answer
    }
  }
}
